### ISSUE TITLE
Add change date field

### ISSUE THREAD

**Issue by FreakTheMighty** [omigos/HubHarvester#16]
Thanks for this great plugin. It has proven to be very useful in huboard and github. It would be helpful to have access to the "Change date" field. I frequently need to back date time tracking when I forget to log hours the day before. I like logging time from huboard or github because it adds the link, but I then have to go to harvest to change the date.

![screen shot 2015-08-11 at 9 52 39 am](https://cloud.githubusercontent.com/assets/247092/9203907/c472848c-400e-11e5-9308-e94cd8c4b21f.png)

**Comment by MassiveHiggsField** [comment]
This is not a feature i can control with my extension. Everything you see inside the popup is loaded directly from harvest. So if you want to access the "change date" feature, you should ask for it here:

https://chrome.google.com/webstore/detail/harvest-time-tracker/fbpiglieekigmkeebmeohkelfpjjlaia/support

**Comment by FreakTheMighty** [comment]
Hmm, there are no options when loading the modal? I seem to remember the
modal looking different from the github harvest extension.

**Comment by MassiveHiggsField** [comment]
You're right, there are some options for the modal. I'll investigate if i can activate this or make it configurable.

**Comment by FreakTheMighty** [comment]
Sweet, thanks!

**Comment by MassiveHiggsField** [comment]
Unfortunately i could not find a way to make this work. The problem is that the modal used in the extension is not the same as used in harvest directly to update the date of an entry. The modal which can be used in the extension only starts/stops the timetracker, it has no control over the entry being created. In theory it would be possible to call the api from harvest, but that would mean i have to create a complete custom modal first, which would be really time-consuming.

**Comment by FreakTheMighty** [comment]
Thanks for looking. For my info, can you point me to the area in your code
responsible for launching the modal?

**Comment by MassiveHiggsField** [comment]
Of course: https://github.com/omigos/HubHarvester/blob/master/src/data/index.js#L100

If you find something, pull requests are always welcome :)

**Comment by FreakTheMighty** [comment]
Will do! Thanks again.

**Comment by FreakTheMighty** [comment]
Yeaaa, harvest says its not possible.

**Comment by MassiveHiggsField** [comment]
Yeah that's what i expected but sad nonetheless.
